//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corgibytes.Freshli.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CliOutput {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CliOutput() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corgibytes.Freshli.Cli.Resources.CliOutput", typeof(CliOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Help_MainCommand_Description {
            get {
                return ResourceManager.GetString("Help_MainCommand_Description", resourceCulture);
            }
        }

        internal static string Help_Option_CacheDir_Description {
            get {
                return ResourceManager.GetString("Help_Option_CacheDir_Description", resourceCulture);
            }
        }

        internal static string Help_CacheCommand_Description {
            get {
                return ResourceManager.GetString("Help_CacheCommand_Description", resourceCulture);
            }
        }

        internal static string Help_CachePrepareCommand_Description {
            get {
                return ResourceManager.GetString("Help_CachePrepareCommand_Description", resourceCulture);
            }
        }

        internal static string Help_CacheDestroyCommand_Description {
            get {
                return ResourceManager.GetString("Help_CacheDestroyCommand_Description", resourceCulture);
            }
        }

        internal static string Help_CacheDestoyCommand_Option_Force {
            get {
                return ResourceManager.GetString("Help_CacheDestoyCommand_Option_Force", resourceCulture);
            }
        }

        internal static string Help_ScanCommand_Description {
            get {
                return ResourceManager.GetString("Help_ScanCommand_Description", resourceCulture);
            }
        }

        internal static string Help_ScanCommand_Option_Format {
            get {
                return ResourceManager.GetString("Help_ScanCommand_Option_Format", resourceCulture);
            }
        }

        internal static string Help_ScanCommand_Option_Output {
            get {
                return ResourceManager.GetString("Help_ScanCommand_Option_Output", resourceCulture);
            }
        }


        internal static string Help_ScanCommand_Argument_Path {
            get {
                return ResourceManager.GetString("Help_ScanCommand_Argument_Path", resourceCulture);
            }
        }

        internal static string Output_Date {
            get {
                return ResourceManager.GetString("Output_Date", resourceCulture);
            }
        }

        internal static string Output_LibYear {
            get {
                return ResourceManager.GetString("Output_LibYear", resourceCulture);
            }
        }

        internal static string Output_Skipped {
            get {
                return ResourceManager.GetString("Output_Skipped", resourceCulture);
            }
        }

        internal static string Output_UpgradesAvailable {
            get {
                return ResourceManager.GetString("Output_UpgradesAvailable", resourceCulture);
            }
        }

        internal static string ScanCommand_ScanCommand_Executing_scan_command_handler {
            get {
                return ResourceManager.GetString("ScanCommand_ScanCommand_Executing_scan_command_handler", resourceCulture);
            }
        }

        internal static string MainCommand_MainCommand_Root_Command_Executed {
            get {
                return ResourceManager.GetString("MainCommand_MainCommand_Root_Command_Executed", resourceCulture);
            }
        }

        internal static string AuthCommand_AuthCommand_Executing_auth_command_handler {
            get {
                return ResourceManager.GetString("AuthCommand_AuthCommand_Executing_auth_command_handler", resourceCulture);
            }
        }

        internal static string ScanCommandRunner_Run_Path_should_not_be_null_or_empty {
            get {
                return ResourceManager.GetString("ScanCommandRunner_Run_Path_should_not_be_null_or_empty", resourceCulture);
            }
        }

        internal static string CachePrepareCommandRunner_Run_Preparing_cache {
            get {
                return ResourceManager.GetString("CachePrepareCommandRunner_Run_Preparing_cache", resourceCulture);
            }
        }

        internal static string CacheDestroyCommandRunner_Run_Prompt {
            get {
                return ResourceManager.GetString("CacheDestroyCommandRunner_Run_Prompt", resourceCulture);
            }
        }

        internal static string CacheDestroyCommandRunner_Run_Abort {
            get {
                return ResourceManager.GetString("CacheDestroyCommandRunner_Run_Abort", resourceCulture);
            }
        }

        internal static string CacheDestroyCommandRunner_Run_Destroying {
            get {
                return ResourceManager.GetString("CacheDestroyCommandRunner_Run_Destroying", resourceCulture);
            }
        }

        internal static string Exception_Cache_Prepare_NonEmpty {
            get {
                return ResourceManager.GetString("Exception_Cache_Prepare_NonEmpty", resourceCulture);
            }
        }

        internal static string Warning_Cache_Destroy_DoesNotExist {
            get {
                return ResourceManager.GetString("Warning_Cache_Destroy_DoesNotExist", resourceCulture);
            }
        }

        internal static string Exception_Cache_Destroy_NonCache {
            get {
                return ResourceManager.GetString("Exception_Cache_Destroy_NonCache", resourceCulture);
            }
        }
    }
}
