version: "2"
exclude_patterns:
  - "Corgibytes.Freshli.Cli/obj/**"
  - "Corgibytes.Freshli.Cli.Test/obj/**"
  - "Corgibytes.Freshli.Cli/Migrations/**"

checks:
  method-lines:
    config:
      threshold: 45
  argument-count:
    enabled: true
    config:
      threshold: 6
  similar-code:
    enabled: false
