version: "2"
checks:
  method-lines:
    config:
      threshold: 30
exclude_patterns:
  - "Corgibytes.Freshli.Cli/obj/**"
  - "Corgibytes.Freshli.Cli.Test/obj/**"
  - "Corgibytes.Freshli.Cli/Migrations/**"

checks:
  method-lines:
    config:
      threshold: 35
  similar-code:
    config:
      threshold: 80
