// <auto-generated />
using System;
using Corgibytes.Freshli.Cli.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Corgibytes.Freshli.Cli.Migrations
{
    [DbContext(typeof(CacheContext))]
    [Migration("20221003205111_AddCachedLibYears")]
    partial class AddCachedLibYears
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7");

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryInterval")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionHistoryMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UseCommitHistory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CachedAnalyses");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedGitSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CachedGitSources");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedHistoryIntervalStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CachedAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GitCommitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CachedAnalysisId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CachedHistoryIntervalStops");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedLibYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryIntervalStopId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestVersion")
                        .HasColumnType("TEXT");

                    b.Property<double>("LibYear")
                        .HasColumnType("REAL");

                    b.Property<string>("PackageName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReleaseDateCurrentVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReleaseDateLatestVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HistoryIntervalStopId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CachedLibYears");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("CachedProperties");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedHistoryIntervalStop", b =>
                {
                    b.HasOne("Corgibytes.Freshli.Cli.DataModel.CachedAnalysis", "CachedAnalysis")
                        .WithMany("HistoryIntervalStops")
                        .HasForeignKey("CachedAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CachedAnalysis");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedLibYear", b =>
                {
                    b.HasOne("Corgibytes.Freshli.Cli.DataModel.CachedHistoryIntervalStop", "HistoryIntervalStop")
                        .WithMany("LibYears")
                        .HasForeignKey("HistoryIntervalStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoryIntervalStop");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedAnalysis", b =>
                {
                    b.Navigation("HistoryIntervalStops");
                });

            modelBuilder.Entity("Corgibytes.Freshli.Cli.DataModel.CachedHistoryIntervalStop", b =>
                {
                    b.Navigation("LibYears");
                });
#pragma warning restore 612, 618
        }
    }
}
