name: EditorConfig Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eclint:
    runs-on: ubuntu-latest
    steps:
      - name: ECLint
        uses: snow-actions/eclint@v1.0.1
